import './index.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastProvider } from './hooks/useToast'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Triviafun',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children:ReactNode
}) {
  return (
    <ToastProvider>
      <div lang="en" className='flex flex-col h-screen w-screen'>
        <body className={inter.className}>{children}</body>
      </div>
    </ToastProvider>
  )
}
